markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: forrestxyuan
author: "xyuan"
email: ######
name: "xyuan个人博客"
url: http://forrestxyuan.github.io
domain: forrestxyuan.github.io
all_categories: [
["Programming", "编程与开发","/posts/programming.html"], 
["read", "读书笔记","/posts/read.html"], 
["lving", "生活随笔","/posts/living.html"],
["about", "关于","/about.html"]
]

paginate: 4
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
